const W=700,H=380,M=28,R=9,PR=19,MINX=M+R,MAXX=W-M-R,MINY=M+R,MAXY=H-M-R,POCKETS=[[M,M],[W/2,M],[W-M,M],[M,H-M],[W/2,H-M],[W-M,H-M]],COLORS={1:'#e3c32f',2:'#2556b9',3:'#d63131',4:'#7041a7',5:'#e57922',6:'#16834b',7:'#8e2727',8:'#161616',9:'#e3c32f',10:'#2556b9',11:'#d63131',12:'#7041a7',13:'#e57922',14:'#16834b',15:'#8e2727'}
export const shotSpeed=v=>120+Math.pow(Math.max(1,Math.min(100,v))/100,1.45)*3080
export const aimStep=(aim,previous,current)=>aim+Math.atan2(Math.sin(current-previous),Math.cos(current-previous))*.5
export function rayToRail(x,y,dx,dy){const tx=dx>0?(MAXX-x)/dx:dx<0?(MINX-x)/dx:Infinity,ty=dy>0?(MAXY-y)/dy:dy<0?(MINY-y)/dy:Infinity;return Math.max(0,Math.min(tx>=0?tx:Infinity,ty>=0?ty:Infinity))}
export function bankPath(x,y,dx,dy,bounces=2){const points=[];for(let i=0;i<bounces;i++){const d=rayToRail(x,y,dx,dy),p={x:x+dx*d,y:y+dy*d};points.push(p);if(Math.abs(p.x-MINX)<.1||Math.abs(p.x-MAXX)<.1)dx=-dx;if(Math.abs(p.y-MINY)<.1||Math.abs(p.y-MAXY)<.1)dy=-dy;x=p.x+dx*.05;y=p.y+dy*.05}return points}
const kind=n=>n===8?'eight':n<8?'solid':'stripe',other=t=>t==='a'?'b':'a',shuffle=a=>a.sort(()=>Math.random()-.5)
function rack(){const nums=shuffle([...Array(7)].map((_,i)=>i+1).concat([...Array(7)].map((_,i)=>i+9))),a=[{x:154,y:190,vx:0,vy:0,on:true,k:'cue',n:0}];nums.splice(4,0,8);let q=0;for(let row=0;row<5;row++)for(let i=0;i<=row;i++){const n=nums[q++];a.push({x:420+row*15.66,y:190+(i-row/2)*18,vx:0,vy:0,on:true,k:kind(n),n})}return a}
export class PoolGame{
 constructor(o){Object.assign(this,o);this.g=this.canvas.getContext('2d');this.me=this.host?'a':'b';this.round=1;this.ready=this.practice;this.power.value=45;this.bind();this.resetRack();this.last=performance.now();this.raf=requestAnimationFrame(t=>this.loop(t));if(this.practice)this.sync()}
 resetRack(){this.balls=rack();this.turn='a';this.phase='aim';this.over=false;this.result='';this.finished=false;this.aiming=false;this.groups={a:null,b:null};this.breakShot=true;this.calledPocket=null;this.ballInHand=false}
 bind(){this.handlers={power:()=>this.powerOut.textContent=this.power.value+'%',down:e=>{if(!this.canControl())return;const p=this.point(e),cue=this.balls[0];if(this.ballInHand){if(!this.validCueSpot(p))return;cue.x=p.x;cue.y=p.y;this.ballInHand=false;this.pendingPlace=[p.x,p.y];this.flash('Ball in hand placed')}if(this.canCallEight()&&!this.calledPocket){this.calledPocket=this.nearestPocket(p);this.flash('8-ball pocket marked');return}const pa=Math.atan2(p.y-cue.y,p.x-cue.x);if(!this.aiming)this.angle=pa;this.aiming=true;this.drag=true;this.pointerAngle=pa;this.canvas.setPointerCapture?.(e.pointerId)},move:e=>{if(!this.drag)return;const p=this.point(e),cue=this.balls[0];if(Math.hypot(p.x-cue.x,p.y-cue.y)<5)return;const a=Math.atan2(p.y-cue.y,p.x-cue.x);this.angle=aimStep(this.angle,this.pointerAngle,a);this.pointerAngle=a},up:e=>{this.handlers.move(e);this.drag=false;this.canvas.releasePointerCapture?.(e.pointerId)},shoot:()=>this.takeShot()};this.power.addEventListener('input',this.handlers.power);this.canvas.addEventListener('pointerdown',this.handlers.down);this.canvas.addEventListener('pointermove',this.handlers.move);this.canvas.addEventListener('pointerup',this.handlers.up);this.shoot.addEventListener('click',this.handlers.shoot)}
 point(e){const r=this.canvas.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width*W,y:(e.clientY-r.top)/r.height*H}}
 nearestPocket(p){return POCKETS.reduce((best,x,i)=>Math.hypot(p.x-x[0],p.y-x[1])<best.d?{i,d:Math.hypot(p.x-x[0],p.y-x[1])}:best,{i:0,d:Infinity}).i}
 validCueSpot(p){return p.x>=MINX&&p.x<=MAXX&&p.y>=MINY&&p.y<=MAXY&&!this.balls.some(b=>b.k!=='cue'&&b.on&&Math.hypot(b.x-p.x,b.y-p.y)<2*R)}
 setReady(v){this.ready=v;this.draw()}
 newRack(){if(!this.over)return;this.round++;this.resetRack();this.sync()}
 group(player=this.turn){return this.groups[player]}
 remaining(group){return this.balls.filter(b=>b.on&&b.k===group).length}
 canCallEight(){return this.group()&&this.remaining(this.group())===0&&this.phase==='aim'&&!this.over}
 canControl(){return this.ready&&this.phase==='aim'&&this.turn===this.me&&!this.over&&this.balls[0]?.on}
 canAim(){return this.canControl()&&!this.ballInHand}
 takeShot(){if(!this.canAim()||!this.aiming)return;const s=shotSpeed(+this.power.value),vx=Math.cos(this.angle)*s,vy=Math.sin(this.angle)*s;this.aiming=false;this.startShot();if(this.host){this.balls[0].vx=vx;this.balls[0].vy=vy}else this.send({t:'shot',vx,vy,place:this.pendingPlace,called:this.calledPocket});this.pendingPlace=null}
 startShot(){this.potted=[];this.scratch=false;this.firstHit=null;this.before=this.group()?this.remaining(this.group()):null;this.phase='roll'}
 receive(m){if(m.t==='state'&&!this.host){this.balls=m.b.map(x=>({x:x[0],y:x[1],on:x[2],k:x[3],n:x[4],vx:0,vy:0}));this.turn=m.turn;this.phase=m.phase;this.over=m.over;this.round=m.round;this.groups=m.groups||this.groups;this.breakShot=!!m.breakShot;this.ballInHand=!!m.ballInHand;this.calledPocket=m.calledPocket;if(m.result&&!this.finished){this.finished=true;this.onFinish({winner:m.result,round:m.round})}}else if(m.t==='shot'&&this.host&&this.turn==='b'&&this.phase==='aim'){if(m.place&&this.validCueSpot({x:m.place[0],y:m.place[1]})){this.balls[0].x=m.place[0];this.balls[0].y=m.place[1];this.ballInHand=false}this.calledPocket=m.called??null;this.startShot();this.balls[0].vx=m.vx;this.balls[0].vy=m.vy}}
 sync(){if(this.host)this.send({t:'state',b:this.balls.map(b=>[Math.round(b.x),Math.round(b.y),b.on,b.k,b.n]),turn:this.turn,phase:this.phase,over:this.over,result:this.result||'',round:this.round,groups:this.groups,breakShot:this.breakShot,ballInHand:this.ballInHand,calledPocket:this.calledPocket})}
 sub(dt){for(const b of this.balls){if(!b.on)continue;b.x+=b.vx*dt;b.y+=b.vy*dt;for(const[p,q]of POCKETS.entries())if(Math.hypot(b.x-q[0],b.y-q[1])<PR){b.on=false;if(b.k==='cue')this.scratch=true;else this.potted.push(b);if(b.k==='eight')this.eightPocket=p;this.flash(b.k==='cue'?'Scratch!':b.k==='eight'?'8-ball potted!':`${b.k==='solid'?'Solid':'Stripe'} ${b.n} potted!`);break}if(!b.on)continue;if(b.x<MINX){b.x=MINX;b.vx=Math.abs(b.vx)*.9}if(b.x>MAXX){b.x=MAXX;b.vx=-Math.abs(b.vx)*.9}if(b.y<MINY){b.y=MINY;b.vy=Math.abs(b.vy)*.9}if(b.y>MAXY){b.y=MAXY;b.vy=-Math.abs(b.vy)*.9}}
  for(let i=0;i<this.balls.length;i++)for(let j=i+1;j<this.balls.length;j++){const a=this.balls[i],b=this.balls[j];if(!a.on||!b.on)continue;const dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy);if(d>0&&d<2*R){if(!this.firstHit){if(a.k==='cue')this.firstHit=b;else if(b.k==='cue')this.firstHit=a}const nx=dx/d,ny=dy/d,ov=2*R-d;a.x-=nx*ov/2;a.y-=ny*ov/2;b.x+=nx*ov/2;b.y+=ny*ov/2;const p=(a.vx-b.vx)*nx+(a.vy-b.vy)*ny;if(p>0){a.vx-=p*nx;a.vy-=p*ny;b.vx+=p*nx;b.vy+=p*ny}}}}
 foul(){const cue=this.balls[0];cue.on=true;cue.vx=cue.vy=0;cue.x=154;cue.y=190;this.ballInHand=true;this.turn=other(this.turn);this.calledPocket=null;this.flash('Foul · ball in hand')}
 finish(winner){this.over=true;this.result=winner;this.finished=true;this.onFinish({winner,round:this.round});this.flash(winner===this.me?'You win!':'You lose')}
 resolve(){const shooter=this.turn,group=this.group(),black=this.potted.some(b=>b.k==='eight'),open=!group,wrongFirst=this.firstHit&&(open?this.firstHit.k==='eight':this.firstHit.k!==(this.before===0?'eight':group));if(black){const legal=this.breakShot?!this.scratch:group&&this.before===0&&!this.scratch&&this.calledPocket===this.eightPocket;this.finish(legal?shooter:other(shooter));this.phase='aim';this.sync();return}if(this.scratch||wrongFirst)this.foul();else{let assigned=false;if(open){const made=this.potted.filter(b=>b.k==='solid'||b.k==='stripe'),groups=[...new Set(made.map(b=>b.k))];if((!this.breakShot&&made[0])||(this.breakShot&&groups.length===1)){const g=this.breakShot?groups[0]:made[0].k;this.groups[shooter]=g;this.groups[other(shooter)]=g==='solid'?'stripe':'solid';assigned=true;this.flash(`${g==='solid'?'Solids':'Stripes'} are yours`)}}const madeOwn=group?this.potted.some(b=>b.k===group):assigned;if(!madeOwn){this.turn=other(shooter);this.calledPocket=null}}this.breakShot=false;this.balls.forEach(b=>b.vx=b.vy=0);this.phase='aim';this.sync();if(this.practice&&!this.over&&this.turn==='b')setTimeout(()=>this.aiShot(),650)}
 aiShot(){if(this.phase!=='aim'||this.over)return;const cue=this.balls[0],g=this.group('b'),targets=this.balls.filter(b=>b.on&&b.k!=='cue'&&(g?b.k===(this.remaining(g)?g:'eight'):b.k!=='eight')),target=targets.sort((a,b)=>Math.hypot(a.x-cue.x,a.y-cue.y)-Math.hypot(b.x-cue.x,b.y-cue.y))[0];if(!target)return;if(target.k==='eight')this.calledPocket=this.nearestPocket(target);const a=Math.atan2(target.y-cue.y,target.x-cue.x)+(Math.random()-.5)*.12,s=shotSpeed(45+Math.random()*30);this.startShot();cue.vx=Math.cos(a)*s;cue.vy=Math.sin(a)*s}
 guide(){const c=this.balls[0],dx=Math.cos(this.angle),dy=Math.sin(this.angle),rail=rayToRail(c.x,c.y,dx,dy);let hit=null,t=rail;for(let i=1;i<this.balls.length;i++){const b=this.balls[i];if(!b.on)continue;const ox=b.x-c.x,oy=b.y-c.y,p=ox*dx+oy*dy,s=ox*ox+oy*oy-p*p;if(p>R&&s<=4*R*R){const z=p-Math.sqrt(4*R*R-s);if(z<t){t=z;hit=b}}}return{c,dx,dy,t,hit,banks:!hit?bankPath(c.x,c.y,dx,dy,2):[]}}
 drawBall(b){const g=this.g;if(b.k==='cue'){g.fillStyle='#fff';g.beginPath();g.arc(b.x,b.y,R,0,7);g.fill()}else{g.fillStyle=COLORS[b.n];g.beginPath();g.arc(b.x,b.y,R,0,7);g.fill();if(b.k==='stripe'){g.save();g.beginPath();g.arc(b.x,b.y,R-.4,0,7);g.clip();g.fillStyle='#f7f3e8';g.fillRect(b.x-R,b.y-4,2*R,8);g.restore()}g.fillStyle='#f7f4e9';g.beginPath();g.arc(b.x,b.y,4.4,0,7);g.fill();g.fillStyle='#182019';g.font='bold 5px Arial';g.textAlign='center';g.textBaseline='middle';g.fillText(b.n,b.x,b.y+.4)}g.fillStyle='rgba(255,255,255,.52)';g.beginPath();g.arc(b.x-3,b.y-3,1.8,0,7);g.fill()}
 draw(){const g=this.g;g.clearRect(0,0,W,H);g.fillStyle='#5f351f';g.fillRect(0,0,W,H);const grad=g.createRadialGradient(350,170,10,350,190,400);grad.addColorStop(0,'#17794b');grad.addColorStop(1,'#06452c');g.fillStyle=grad;g.fillRect(22,22,656,336);g.fillStyle='#07100c';POCKETS.forEach(([x,y],i)=>{g.beginPath();g.arc(x,y,PR-2,0,7);g.fill();if(this.calledPocket===i){g.strokeStyle='#ffd75d';g.lineWidth=3;g.beginPath();g.arc(x,y,PR+3,0,7);g.stroke()}});for(const b of this.balls)if(b.on)this.drawBall(b)
  if(this.aiming&&this.canAim()){const q=this.guide();g.lineWidth=1.2;g.setLineDash([7,6]);g.strokeStyle='#fff';g.beginPath();g.moveTo(q.c.x,q.c.y);g.lineTo(q.c.x+q.dx*q.t,q.c.y+q.dy*q.t);g.stroke();if(q.banks.length){g.strokeStyle='rgba(255,255,255,.48)';g.beginPath();g.moveTo(q.banks[0].x,q.banks[0].y);q.banks.slice(1).forEach(p=>g.lineTo(p.x,p.y));g.stroke()}if(q.hit){const gx=q.c.x+q.dx*q.t,gy=q.c.y+q.dy*q.t,nx=(q.hit.x-gx)/(2*R),ny=(q.hit.y-gy)/(2*R),d=rayToRail(q.hit.x,q.hit.y,nx,ny);g.strokeStyle='#ffd96a';g.beginPath();g.moveTo(q.hit.x,q.hit.y);g.lineTo(q.hit.x+nx*d,q.hit.y+ny*d);g.stroke()}g.setLineDash([]);const tip=R+6+(+this.power.value/100)*42,at=d=>[q.c.x-q.dx*(tip+d),q.c.y-q.dy*(tip+d)];g.lineCap='round';for(const [a,b,w,c]of [[0,5,4,'#4e8fa6'],[5,52,7,'#ece0bb'],[52,160,9,'#a76f38'],[160,205,11,'#1d1915'],[205,242,14,'#714326']]){g.strokeStyle=c;g.lineWidth=w;g.beginPath();g.moveTo(...at(a));g.lineTo(...at(b));g.stroke()}g.lineCap='butt'}
  const mine=this.group(this.me),their=this.group(other(this.me)),label=x=>x?x==='solid'?'Solids':'Stripes':'Open table';this.shoot.disabled=!this.canAim()||!this.aiming;this.status.textContent=!this.ready?'Waiting for another player…':this.over?(this.result===this.me?'You won the rack':'Opponent won the rack'):this.turn===this.me?(this.ballInHand?'Ball in hand · tap table to place cue':this.canCallEight()&&!this.calledPocket?'Mark an 8-ball pocket, then aim':`${label(mine)} · your shot`):this.practice?'AI is lining up…':`${label(their)} · opponent’s turn`}
 loop(t){const dt=Math.min(.033,(t-this.last)/1000||0);this.last=t;if(this.host&&this.phase==='roll'){for(let i=0;i<7;i++)this.sub(dt/7);for(const b of this.balls){b.vx*=.989;b.vy*=.989}if(t-(this.sent||0)>40){this.sent=t;this.sync()}if(this.balls.every(b=>!b.on||(Math.abs(b.vx)<5&&Math.abs(b.vy)<5)))this.resolve()}this.draw();this.raf=requestAnimationFrame(x=>this.loop(x))}
 flash(s){this.callout.textContent=s;this.callout.classList.add('show');clearTimeout(this.ft);this.ft=setTimeout(()=>this.callout.classList.remove('show'),1000)}
 destroy(){cancelAnimationFrame(this.raf);clearTimeout(this.ft);this.power.removeEventListener('input',this.handlers.power);this.canvas.removeEventListener('pointerdown',this.handlers.down);this.canvas.removeEventListener('pointermove',this.handlers.move);this.canvas.removeEventListener('pointerup',this.handlers.up);this.shoot.removeEventListener('click',this.handlers.shoot)}
}
