const W=700,H=380,M=28,R=9,PR=19,MINX=M+R,MAXX=W-M-R,MINY=M+R,MAXY=H-M-R,POCKETS=[[M,M],[W/2,M],[W-M,M],[M,H-M],[W/2,H-M],[W-M,H-M]]
export const shotSpeed=v=>120+Math.pow(Math.max(1,Math.min(100,v))/100,1.45)*3080
export function rayToRail(x,y,dx,dy){const tx=dx>0?(MAXX-x)/dx:dx<0?(MINX-x)/dx:Infinity,ty=dy>0?(MAXY-y)/dy:dy<0?(MINY-y)/dy:Infinity;return Math.max(0,Math.min(tx>=0?tx:Infinity,ty>=0?ty:Infinity))}
export function bankPath(x,y,dx,dy,bounces=2){const points=[];for(let i=0;i<bounces;i++){const d=rayToRail(x,y,dx,dy),p={x:x+dx*d,y:y+dy*d};points.push(p);if(Math.abs(p.x-MINX)<.1||Math.abs(p.x-MAXX)<.1)dx=-dx;if(Math.abs(p.y-MINY)<.1||Math.abs(p.y-MAXY)<.1)dy=-dy;x=p.x+dx*.05;y=p.y+dy*.05}return points}
function rack(){const a=[{x:154,y:190,vx:0,vy:0,on:true,c:'w'}],cols=[...Array(7).fill('r'),...Array(7).fill('y')].sort(()=>Math.random()-.5);cols.splice(4,0,'k');let k=0;for(let row=0;row<5;row++)for(let i=0;i<=row;i++)a.push({x:420+row*15.66,y:190+(i-row/2)*18,vx:0,vy:0,on:true,c:cols[k++]});return a}
export class PoolGame{
 constructor(o){Object.assign(this,o);this.g=this.canvas.getContext('2d');this.me=this.host?'a':'b';this.balls=this.host?rack():[];this.turn='a';this.phase='aim';this.over=false;this.round=1;this.ready=this.practice;this.aiming=false;this.power.value=45;this.bind();this.last=performance.now();this.raf=requestAnimationFrame(t=>this.loop(t));if(this.practice)this.sync()}
 bind(){this.handlers={power:()=>this.powerOut.textContent=this.power.value+'%',down:e=>{if(!this.canAim())return;const p=this.point(e),c=this.balls[0],pa=Math.atan2(p.y-c.y,p.x-c.x);if(!this.aiming)this.angle=pa;this.aiming=true;this.drag=true;this.startAngle=this.angle;this.pointerAngle=pa;this.canvas.setPointerCapture?.(e.pointerId)},move:e=>{if(!this.drag)return;const p=this.point(e),c=this.balls[0],a=Math.atan2(p.y-c.y,p.x-c.x),d=Math.atan2(Math.sin(a-this.pointerAngle),Math.cos(a-this.pointerAngle));this.angle=this.startAngle+d*.5},up:e=>{this.handlers.move(e);this.drag=false;this.canvas.releasePointerCapture?.(e.pointerId)},shoot:()=>this.takeShot()};this.power.addEventListener('input',this.handlers.power);this.canvas.addEventListener('pointerdown',this.handlers.down);this.canvas.addEventListener('pointermove',this.handlers.move);this.canvas.addEventListener('pointerup',this.handlers.up);this.shoot.addEventListener('click',this.handlers.shoot)}
 point(e){const r=this.canvas.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width*W,y:(e.clientY-r.top)/r.height*H}}
 setReady(v){this.ready=v;this.draw()}
 canAim(){return this.ready&&this.phase==='aim'&&this.turn===this.me&&!this.over&&this.balls[0]?.on}
 takeShot(){if(!this.canAim()||!this.aiming)return;const s=shotSpeed(+this.power.value),vx=Math.cos(this.angle)*s,vy=Math.sin(this.angle)*s;this.aiming=false;if(this.host){this.balls[0].vx=vx;this.balls[0].vy=vy;this.potted=[];this.scratch=false;this.phase='roll'}else{this.phase='roll';this.send({t:'shot',vx,vy})}}
 receive(m){if(m.t==='state'&&!this.host){this.balls=m.b.map(x=>({x:x[0],y:x[1],on:x[2],c:x[3]}));this.turn=m.turn;this.phase=m.phase;this.over=m.over;this.round=m.round;if(m.result&&!this.finished){this.finished=true;this.onFinish({winner:m.result,round:m.round})}}else if(m.t==='shot'&&this.host&&this.turn==='b'&&this.phase==='aim'){this.balls[0].vx=m.vx;this.balls[0].vy=m.vy;this.potted=[];this.scratch=false;this.phase='roll'}}
 sync(){if(this.host)this.send({t:'state',b:this.balls.map(b=>[Math.round(b.x),Math.round(b.y),b.on,b.c]),turn:this.turn,phase:this.phase,over:this.over,result:this.result||'',round:this.round})}
 sub(dt){for(const b of this.balls){if(!b.on)continue;b.x+=b.vx*dt;b.y+=b.vy*dt;for(const[p,q]of POCKETS)if(Math.hypot(b.x-p,b.y-q)<PR){b.on=false;if(b.c==='w')this.scratch=true;else this.potted.push(b.c);this.flash(b.c==='w'?'Scratch!':b.c==='k'?'Black potted!':`${b.c==='r'?'Red':'Yellow'} potted!`);break}if(!b.on)continue;if(b.x<MINX){b.x=MINX;b.vx=Math.abs(b.vx)*.9}if(b.x>MAXX){b.x=MAXX;b.vx=-Math.abs(b.vx)*.9}if(b.y<MINY){b.y=MINY;b.vy=Math.abs(b.vy)*.9}if(b.y>MAXY){b.y=MAXY;b.vy=-Math.abs(b.vy)*.9}}
  for(let i=0;i<this.balls.length;i++)for(let j=i+1;j<this.balls.length;j++){const a=this.balls[i],b=this.balls[j];if(!a.on||!b.on)continue;const dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy);if(d>0&&d<2*R){const nx=dx/d,ny=dy/d,ov=2*R-d;a.x-=nx*ov/2;a.y-=ny*ov/2;b.x+=nx*ov/2;b.y+=ny*ov/2;const p=(a.vx-b.vx)*nx+(a.vy-b.vy)*ny;if(p>0){a.vx-=p*nx;a.vy-=p*ny;b.vx+=p*nx;b.vy+=p*ny}}}}
 colors(c){return this.balls.filter(b=>b.on&&b.c===c).length}
 resolve(){const col=this.turn==='a'?'r':'y';if(!this.colors('k')){this.over=true;this.result=!this.colors(col)?this.turn:this.turn==='a'?'b':'a';this.finished=true;this.onFinish({winner:this.result,round:this.round});this.flash(this.result===this.me?'You win!':'You lose')}else if(this.scratch){const c=this.balls[0];c.on=true;c.x=154;c.y=190;c.vx=c.vy=0;this.turn=this.turn==='a'?'b':'a'}else if(!this.potted.filter(x=>x===col).length)this.turn=this.turn==='a'?'b':'a';this.balls.forEach(b=>b.vx=b.vy=0);this.phase='aim';this.sync();if(this.practice&&!this.over&&this.turn==='b')setTimeout(()=>this.aiShot(),700)}
 aiShot(){if(this.phase!=='aim'||this.over)return;const cue=this.balls[0],targets=this.balls.filter(b=>b.on&&b.c!=='w'&&(b.c==='y'||(!this.colors('y')&&b.c==='k'))),target=targets.sort((a,b)=>Math.hypot(a.x-cue.x,a.y-cue.y)-Math.hypot(b.x-cue.x,b.y-cue.y))[0];if(!target)return;let a=Math.atan2(target.y-cue.y,target.x-cue.x)+(Math.random()-.5)*.12,s=shotSpeed(45+Math.random()*30);cue.vx=Math.cos(a)*s;cue.vy=Math.sin(a)*s;this.potted=[];this.scratch=false;this.phase='roll'}
 guide(){const c=this.balls[0],dx=Math.cos(this.angle),dy=Math.sin(this.angle),rail=rayToRail(c.x,c.y,dx,dy);let hit=null,t=rail;for(let i=1;i<this.balls.length;i++){const b=this.balls[i];if(!b.on)continue;const ox=b.x-c.x,oy=b.y-c.y,p=ox*dx+oy*dy,s=ox*ox+oy*oy-p*p;if(p>R&&s<=4*R*R){const z=p-Math.sqrt(4*R*R-s);if(z<t){t=z;hit=b}}}return{c,dx,dy,t,hit,banks:!hit?bankPath(c.x,c.y,dx,dy,2):[]}}
 draw(){const g=this.g;g.clearRect(0,0,W,H);g.fillStyle='#5f351f';g.fillRect(0,0,W,H);const grad=g.createRadialGradient(350,170,10,350,190,400);grad.addColorStop(0,'#17794b');grad.addColorStop(1,'#06452c');g.fillStyle=grad;g.fillRect(22,22,656,336);g.fillStyle='#07100c';POCKETS.forEach(([x,y])=>{g.beginPath();g.arc(x,y,PR-2,0,7);g.fill()});const fill={w:'#fff',r:'#e54444',y:'#f1c83e',k:'#111'};for(const b of this.balls)if(b.on){g.fillStyle=fill[b.c];g.beginPath();g.arc(b.x,b.y,R,0,7);g.fill();g.fillStyle='rgba(255,255,255,.55)';g.beginPath();g.arc(b.x-3,b.y-3,2,0,7);g.fill()}
  if(this.aiming&&this.canAim()){const q=this.guide();g.lineWidth=1.2;g.setLineDash([7,6]);g.strokeStyle='#fff';g.beginPath();g.moveTo(q.c.x,q.c.y);g.lineTo(q.c.x+q.dx*q.t,q.c.y+q.dy*q.t);g.stroke();if(q.banks.length){g.strokeStyle='rgba(255,255,255,.48)';let p=q.banks[0];g.beginPath();g.moveTo(p.x,p.y);for(let i=1;i<q.banks.length;i++)g.lineTo(q.banks[i].x,q.banks[i].y);g.stroke()}if(q.hit){const gx=q.c.x+q.dx*q.t,gy=q.c.y+q.dy*q.t,nx=(q.hit.x-gx)/(2*R),ny=(q.hit.y-gy)/(2*R),d=rayToRail(q.hit.x,q.hit.y,nx,ny);g.strokeStyle='#ffd96a';g.beginPath();g.moveTo(q.hit.x,q.hit.y);g.lineTo(q.hit.x+nx*d,q.hit.y+ny*d);g.stroke();const banks=bankPath(q.hit.x,q.hit.y,nx,ny,2);g.strokeStyle='rgba(255,217,106,.45)';g.beginPath();g.moveTo(banks[0].x,banks[0].y);g.lineTo(banks[1].x,banks[1].y);g.stroke()}g.setLineDash([]);const back=R+8+(+this.power.value/100)*50;g.strokeStyle='#d4aa64';g.lineWidth=7;g.beginPath();g.moveTo(q.c.x-q.dx*back,q.c.y-q.dy*back);g.lineTo(q.c.x-q.dx*(back+170),q.c.y-q.dy*(back+170));g.stroke()}
  this.shoot.disabled=!this.canAim()||!this.aiming;this.status.textContent=!this.ready?'Waiting for another player…':this.over?(this.result===this.me?'You won the rack':'Opponent won the rack'):this.turn===this.me?(this.phase==='aim'?'Your shot · drag on the table to aim':'Balls rolling…'):(this.practice?'AI is lining up…':'Opponent’s turn')}
 loop(t){const dt=Math.min(.033,(t-this.last)/1000||0);this.last=t;if(this.host&&this.phase==='roll'){for(let i=0;i<7;i++)this.sub(dt/7);for(const b of this.balls){b.vx*=.989;b.vy*=.989}if(t-(this.sent||0)>40){this.sent=t;this.sync()}if(this.balls.every(b=>!b.on||(Math.abs(b.vx)<5&&Math.abs(b.vy)<5)))this.resolve()}this.draw();this.raf=requestAnimationFrame(x=>this.loop(x))}
 flash(s){this.callout.textContent=s;this.callout.classList.add('show');clearTimeout(this.ft);this.ft=setTimeout(()=>this.callout.classList.remove('show'),1000)}
 destroy(){cancelAnimationFrame(this.raf);clearTimeout(this.ft);this.power.removeEventListener('input',this.handlers.power);this.canvas.removeEventListener('pointerdown',this.handlers.down);this.canvas.removeEventListener('pointermove',this.handlers.move);this.canvas.removeEventListener('pointerup',this.handlers.up);this.shoot.removeEventListener('click',this.handlers.shoot)}
}
